# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rego-ruby-ext 0.0.7 ruby lib

Gem::Specification.new do |s|
  s.name = "rego-ruby-ext"
  s.version = "0.0.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Alex Tkachev"]
  s.date = "2015-12-15"
  s.description = "Ruby core extensions that are common for all ReGO projects"
  s.email = "tkachev.alex@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "init.rb",
    "lib/boolean-ext.rb",
    "lib/date-ext.rb",
    "lib/enumerable-ext.rb",
    "lib/nil-ext.rb",
    "lib/numeric-ext.rb",
    "lib/rego-ruby-ext.rb",
    "lib/string-ext.rb",
    "lib/string-interpolation.rb",
    "lib/symbol-ext.rb",
    "lib/time-ext.rb",
    "rego-ruby-ext.gemspec",
    "spec/boolean_spec.rb",
    "spec/date_spec.rb",
    "spec/enumerable_spec.rb",
    "spec/nil_spec.rb",
    "spec/numeric_spec.rb",
    "spec/rego-ruby-ext_spec.rb",
    "spec/spec_helper.rb",
    "spec/string_interpolation_spec.rb",
    "spec/string_spec.rb",
    "spec/symbol_spec.rb",
    "spec/time_spec.rb"
  ]
  s.homepage = "http://github.com/alextk/rego-ruby-ext"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.6"
  s.summary = "Some basic ruby core classes extensions with tests"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.8"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.8"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.8"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

